### ISSUE TITLE
本项目在Xavier平台的安装问题

### ISSUE THREAD

**Issue by Hyper-Devil** [bitfsd/darknet_ros#1]
感谢BITFSD的开源工作。

我在将本项目部署到Xavier平台时遇到如下错误：

In file included from /usr/include/opencv4/opencv2/core/types_c.h:82:0,
                 from /usr/include/opencv4/opencv2/core/core_c.h:48,
                 from /usr/include/opencv4/opencv2/imgproc/types_c.h:46,
                 from /usr/include/opencv4/opencv2/imgproc/imgproc_c.h:46,
                 from /home/mct/whd/catkin_darknet_bit/src/darknet_ros-master/darknet_ros/include/darknet_ros/image_interface.h:13,
                 from /home/mct/whd/catkin_darknet_bit/src/darknet_ros-master/darknet_ros/src/image_interface.c:9:
/usr/include/opencv4/opencv2/core/cvdef.h:690:4: error: #error "OpenCV 4.x+ requires enabled C++11 support"
 #  error "OpenCV 4.x+ requires enabled C++11 support"
compilation terminated due to -Wfatal-errors.

我已经在各目录下的CMakeLists.txt中加入了set(CMAKE_CXX_STANDARD 11)，所以我不明白为什么依然会出现这个问题，期待得到解答，感谢。

**Comment by Feng1909** [comment]
尝试 `set(CMAKE_CXX_STANDARD 14)` 呢，报错信息指C++11不支持OpenCV4.x，所以应该设置C++14或者其他版本

**Comment by Feng1909** [comment]
尝试 `set(CMAKE_CXX_STANDARD 14)` 呢，报错信息指C++11不支持OpenCV4.x，所以应该设置C++14或者其他版本。
另外，我们推荐使用ros自带的opencv，可以尝试将opencv降级到3.2版本

**Comment by Hyper-Devil** [comment]
感谢您的回复。

set(CMAKE_CXX_STANDARD 14)与catkin_make -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-std=c++14"似乎并不能解决该问题，我后续将尝试降级opencv版本。

降级opencv3.4.1该问题解决。
